version: '3.9'

services:
  log-serv-app:
    build: 
      dockerfile: ./Dockerfile
    container_name: logserv
    restart: unless-stopped
    ports:
      - "5001:5001"
    depends_on:
      - log-db
    networks:
      - service-network
  log-db:
    image: postgres:14.1-alpine
    ports:
      - 5433:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=log_service
      - POSTGRES_USER=dakz
      - POSTGRES_PASSWORD=123321
    networks:
      - service-network
networks:
  service-network:
    external: true
