version: '3.9'

services:
  db:
    image: postgres:14.1-alpine
    ports:
      - 5433:5433
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=log_service
      - POSTGRES_USER=dakz
      - POSTGRES_PASSWORD=123321
